### ISSUE TITLE
Some Questions

### ISSUE THREAD

**Issue by LIUkhan** [zwt233/NDLS#1]
Hi wentao! Excellent work!!!  Due to my poor capability of math , I raise the following questions for the paper:
when a connected graph with the adjacent matrix A without self-loop and using r=0.5(Acap = D{^0.5}AD{^0.5} ) is used,
will the Eq. 2 in the paper become : Acap-infinity =  sqrt(di)*sqrt(dj)/ (2m + n) ?
will the Theorem 3.1. become:  (di +1) in the Eq. 6 to di ?
will the Theorem 3.2. still be corret?
and are there some tips to choose a proper epsilon for a specific task? 
thank you for reading this issue!

**Comment by zwt233** [comment]
> when a connected graph with the adjacent matrix A without self-loop and using r=0.5(Acap = D{^0.5}AD{^0.5} ) is used,
will the Eq. 2 in the paper become : Acap-infinity = sqrt(di)*sqrt(dj)/ (2m + n) ?
ANSWER: Yes.

> will the Theorem 3.1. become: (di +1) in the Eq. 6 to di ?
ANSWER: In the Theorem 3.1 \tilde{di} denotes (di+1), but when you set r=0.5, Theorem 3.1 may not hold.

> will the Theorem 3.2. still be corret?
ANSWER: Yes, Theorem 3.2 is not limited to r.

> and are there some tips to choose a proper epsilon for a specific task?
ANSWER: Maybe you could calculate the average distance from the inital state to the final state dis, and set epsilon as dis/10 or others.

**Comment by LIUkhan** [comment]
> will the Eq. 2 in the paper become : Acap-infinity = sqrt(di)*sqrt(dj)/ (2m + n) ?
> ANSWER: Yes.
Thanks for your immediate and kind reply!!!!
-  An extra check for this question when I rethink my quesiton:
- [√ ]  Acap-infinity = sqrt(di)*sqrt(dj)/ (2m + n) ？
- [ ×]  Acap-infinity = sqrt(di)*sqrt(dj)/ (2m)       ？ without self-loop, the A mat only has 2m non-zero elements

**Comment by zwt233** [comment]
> > will the Eq. 2 in the paper become : Acap-infinity = sqrt(di)*sqrt(dj)/ (2m + n) ?
> > ANSWER: Yes.
> > Thanks for your immediate and kind reply!!!!
> 
> * An extra check for this question when I rethink my quesiton:
> * [√ ]  Acap-infinity = sqrt(di)*sqrt(dj)/ (2m + n) ？
> * [ ×]  Acap-infinity = sqrt(di)*sqrt(dj)/ (2m)       ？ without self-loop, the A mat only has 2m non-zero elements

Mathematically, sqrt(di)*sqrt(dj)/ (2m) is correct without self loop. But in many real application (e.g., node classification and node clustering), the graph information of node itself cannot be ultilized if we ignore self loop, leading to non-optimal model performance.

**Comment by LIUkhan** [comment]
Thanks for your kind advise! I want to do an experiment to extend LightGCN with LIS . Due to its adjacent matrix does not contain self-loop,  I ask these quesitons
